// ===== PRODUCT DATA =====

const phoneCovers = [
    {
        id: 'pc001',
        title: 'Premium Silicone Case - Matte Finish Anti-Fingerprint',
        price: 250,
        originalPrice: 500,
        discount: 50,
        rating: 4.8,
        sold: 2500,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 14', 'iPhone 14 Pro', 'iPhone 13', 'Samsung S24', 'Samsung S24 Ultra', 'Samsung S23', 'Samsung A54', 'Samsung A34', 'Xiaomi 14', 'Xiaomi 13', 'Oppo Reno 11', 'Vivo V30'],
        colors: ['#000000', '#ffffff', '#1a237e', '#b71c1c', '#1b5e20', '#4a148c', '#ff6f00'],
        colorNames: ['Black', 'White', 'Navy Blue', 'Red', 'Green', 'Purple', 'Orange'],
        images: ['https://placehold.co/400x400/333/fff?text=Silicone+Case', 'https://placehold.co/400x400/1a237e/fff?text=Navy+Blue', 'https://placehold.co/400x400/b71c1c/fff?text=Red'],
        description: 'Ultra-thin premium silicone case with matte finish. Anti-fingerprint coating, precise cutouts, and raised edges for camera protection.',
        features: ['Anti-fingerprint matte finish', 'Raised camera protection', 'Precise button cutouts', 'Wireless charging compatible', 'Slim 1.2mm thickness']
    },
    {
        id: 'pc002',
        title: 'Transparent Clear Case - Shockproof TPU Back Cover',
        price: 150,
        originalPrice: 350,
        discount: 57,
        rating: 4.6,
        sold: 5200,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 14', 'iPhone 14 Pro', 'iPhone 13', 'Samsung S24', 'Samsung S24 Ultra', 'Samsung S23', 'Samsung A54', 'Samsung A34', 'Xiaomi 14', 'Xiaomi 13'],
        colors: ['#f5f5f5', '#ffe0e0', '#e0f0ff', '#e0ffe0'],
        colorNames: ['Crystal Clear', 'Rose Tint', 'Blue Tint', 'Green Tint'],
        images: ['https://placehold.co/400x400/f5f5f5/333?text=Clear+Case', 'https://placehold.co/400x400/ffe0e0/333?text=Rose+Tint', 'https://placehold.co/400x400/e0f0ff/333?text=Blue+Tint'],
        description: 'Crystal clear transparent case that showcases your phone design. Shockproof TPU material with air cushion corners.',
        features: ['Crystal clear transparency', 'Shockproof air cushion corners', 'Non-yellowing material', 'Slim and lightweight', 'Easy to install']
    },
    {
        id: 'pc003',
        title: 'Leather Wallet Case - Card Holder Flip Cover',
        price: 450,
        originalPrice: 800,
        discount: 44,
        rating: 4.7,
        sold: 1800,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 14', 'iPhone 14 Pro', 'Samsung S24', 'Samsung S24 Ultra', 'Samsung S23', 'Samsung A54'],
        colors: ['#3e2723', '#000000', '#1a237e', '#b71c1c', '#795548'],
        colorNames: ['Brown', 'Black', 'Navy', 'Wine Red', 'Tan'],
        images: ['https://placehold.co/400x400/3e2723/fff?text=Leather+Case', 'https://placehold.co/400x400/000/fff?text=Black+Leather', 'https://placehold.co/400x400/1a237e/fff?text=Navy+Leather'],
        description: 'Premium PU leather wallet case with card slots and cash pocket. Magnetic closure with kickstand function.',
        features: ['3 card slots + cash pocket', 'Magnetic snap closure', 'Kickstand function', 'Full 360 protection', 'RFID blocking']
    },
    {
        id: 'pc004',
        title: 'Armor Heavy Duty Case - Military Grade Protection',
        price: 380,
        originalPrice: 700,
        discount: 46,
        rating: 4.9,
        sold: 3100,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 14', 'iPhone 14 Pro', 'Samsung S24', 'Samsung S24 Ultra', 'Samsung S23', 'Xiaomi 14', 'Oppo Reno 11'],
        colors: ['#000000', '#1b5e20', '#0d47a1', '#b71c1c', '#37474f'],
        colorNames: ['Black', 'Army Green', 'Blue', 'Red', 'Gunmetal'],
        images: ['https://placehold.co/400x400/37474f/fff?text=Armor+Case', 'https://placehold.co/400x400/1b5e20/fff?text=Army+Green', 'https://placehold.co/400x400/0d47a1/fff?text=Blue'],
        description: 'Military-grade drop protection with dual-layer design. Built-in kickstand and enhanced grip texture.',
        features: ['Military-grade MIL-STD-810G', 'Dual-layer protection', 'Built-in kickstand', 'Enhanced grip texture', 'Port covers for dust protection']
    },
    {
        id: 'pc005',
        title: 'Cute Cartoon Character Case - 3D Silicone Design',
        price: 320,
        originalPrice: 550,
        discount: 42,
        rating: 4.5,
        sold: 4200,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 14', 'iPhone 13', 'Samsung S24', 'Samsung S23', 'Samsung A54', 'Samsung A34', 'Xiaomi 14', 'Xiaomi 13'],
        colors: ['#ffcdd2', '#bbdefb', '#c8e6c9', '#fff9c4', '#e1bee7'],
        colorNames: ['Pink Bear', 'Blue Bunny', 'Green Dino', 'Yellow Duck', 'Purple Cat'],
        images: ['https://placehold.co/400x400/ffcdd2/333?text=Cute+Bear', 'https://placehold.co/400x400/bbdefb/333?text=Blue+Bunny', 'https://placehold.co/400x400/c8e6c9/333?text=Green+Dino'],
        description: '3D cute cartoon character design with soft silicone material. Fun and colorful protection for your phone.',
        features: ['3D character design', 'Soft food-grade silicone', 'Shockproof cushion', 'Lanyard hole included', 'Washable material']
    },
    {
        id: 'pc006',
        title: 'Magnetic MagSafe Compatible Case - Premium Feel',
        price: 550,
        originalPrice: 1000,
        discount: 45,
        rating: 4.8,
        sold: 1500,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 14', 'iPhone 14 Pro', 'iPhone 14 Pro Max'],
        colors: ['#000000', '#1a237e', '#4a148c', '#004d40', '#bf360c'],
        colorNames: ['Black', 'Midnight Blue', 'Deep Purple', 'Forest Green', 'Burnt Orange'],
        images: ['https://placehold.co/400x400/1a237e/fff?text=MagSafe+Case', 'https://placehold.co/400x400/4a148c/fff?text=Purple', 'https://placehold.co/400x400/004d40/fff?text=Green'],
        description: 'Built-in strong magnets compatible with MagSafe accessories. Premium matte finish with silky smooth texture.',
        features: ['Strong MagSafe magnets', 'Supports wireless charging', 'Silky matte texture', 'Microfiber lining', 'Precise alignment']
    },
    {
        id: 'pc007',
        title: 'Ring Holder Case - 360 Rotation Kickstand',
        price: 280,
        originalPrice: 480,
        discount: 42,
        rating: 4.4,
        sold: 3800,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 14', 'iPhone 13', 'Samsung S24', 'Samsung S23', 'Samsung A54', 'Xiaomi 14', 'Oppo Reno 11', 'Vivo V30'],
        colors: ['#000000', '#c62828', '#1565c0', '#2e7d32', '#e65100'],
        colorNames: ['Black', 'Red', 'Blue', 'Green', 'Orange'],
        images: ['https://placehold.co/400x400/000/fff?text=Ring+Case', 'https://placehold.co/400x400/c62828/fff?text=Red+Ring', 'https://placehold.co/400x400/1565c0/fff?text=Blue+Ring'],
        description: 'Slim case with built-in 360-degree rotation ring holder. Perfect grip and doubles as a kickstand.',
        features: ['360-degree ring rotation', 'Doubles as kickstand', 'Magnetic car mount compatible', 'Slim profile', 'Anti-drop design']
    },
    {
        id: 'pc008',
        title: 'Gradient Glass Back Case - Luxury Mirror Finish',
        price: 420,
        originalPrice: 750,
        discount: 44,
        rating: 4.7,
        sold: 2900,
        category: 'phone-cover',
        models: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 14', 'Samsung S24', 'Samsung S24 Ultra', 'Samsung S23', 'Xiaomi 14'],
        colors: ['#1a237e', '#880e4f', '#004d40', '#311b92', '#bf360c'],
        colorNames: ['Blue-Purple', 'Pink-Red', 'Green-Blue', 'Purple-Blue', 'Orange-Red'],
        images: ['https://placehold.co/400x400/1a237e/fff?text=Gradient+Blue', 'https://placehold.co/400x400/880e4f/fff?text=Pink+Gradient', 'https://placehold.co/400x400/004d40/fff?text=Green+Gradient'],
        description: 'Stunning gradient tempered glass back with soft TPU bumper frame. Mirror-like finish that stands out.',
        features: ['Tempered glass back', 'Beautiful gradient colors', 'Anti-scratch coating', 'Soft TPU bumper', 'Oleophobic coating']
    }
];


const ladiesDresses = [
    {
        id: 'ld001',
        title: 'Elegant Floral Print Maxi Dress - Summer Collection',
        price: 850,
        originalPrice: 1500,
        discount: 43,
        rating: 4.7,
        sold: 1200,
        category: 'ladies-dress',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#c62828', '#1565c0', '#2e7d32', '#000000', '#e91e63'],
        colorNames: ['Red Floral', 'Blue Floral', 'Green Floral', 'Black Floral', 'Pink Floral'],
        style: 'Maxi',
        images: ['https://placehold.co/400x500/c62828/fff?text=Red+Floral+Maxi', 'https://placehold.co/400x500/1565c0/fff?text=Blue+Floral', 'https://placehold.co/400x500/2e7d32/fff?text=Green+Floral'],
        description: 'Beautiful floral print maxi dress perfect for summer outings. Lightweight and breathable fabric with flattering A-line silhouette.',
        features: ['Lightweight chiffon fabric', 'A-line flattering cut', 'Adjustable waist tie', 'Lined bodice', 'Machine washable']
    },
    {
        id: 'ld002',
        title: 'Korean Style Casual Mini Dress - Puff Sleeves',
        price: 650,
        originalPrice: 1200,
        discount: 46,
        rating: 4.6,
        sold: 2800,
        category: 'ladies-dress',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#fff8e1', '#e8f5e9', '#fce4ec', '#e3f2fd', '#f3e5f5'],
        colorNames: ['Cream', 'Mint Green', 'Baby Pink', 'Sky Blue', 'Lavender'],
        style: 'Mini',
        images: ['https://placehold.co/400x500/fff8e1/333?text=Cream+Mini', 'https://placehold.co/400x500/e8f5e9/333?text=Mint+Green', 'https://placehold.co/400x500/fce4ec/333?text=Baby+Pink'],
        description: 'Trendy Korean-style mini dress with adorable puff sleeves. Perfect for casual outings and daily wear.',
        features: ['Cute puff sleeves', 'Square neckline', 'Back zipper closure', 'Above knee length', 'Cotton blend fabric']
    },
    {
        id: 'ld003',
        title: 'Office Formal Midi Dress - Bodycon Pencil Style',
        price: 980,
        originalPrice: 1800,
        discount: 46,
        rating: 4.8,
        sold: 950,
        category: 'ladies-dress',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#000000', '#1a237e', '#880e4f', '#37474f', '#4a148c'],
        colorNames: ['Black', 'Navy', 'Burgundy', 'Charcoal', 'Purple'],
        style: 'Midi',
        images: ['https://placehold.co/400x500/000/fff?text=Black+Formal', 'https://placehold.co/400x500/1a237e/fff?text=Navy+Formal', 'https://placehold.co/400x500/880e4f/fff?text=Burgundy'],
        description: 'Sophisticated bodycon pencil dress for the modern professional woman. Sleek silhouette with comfortable stretch fabric.',
        features: ['Stretch ponte fabric', 'Knee-length pencil cut', 'Back slit for ease', 'Hidden back zipper', 'Fully lined']
    },
    {
        id: 'ld004',
        title: 'Bohemian Beach Dress - Loose Fit with Tassels',
        price: 750,
        originalPrice: 1300,
        discount: 42,
        rating: 4.5,
        sold: 1600,
        category: 'ladies-dress',
        sizes: ['Free Size', 'S', 'M', 'L', 'XL'],
        colors: ['#fff3e0', '#e0f7fa', '#fce4ec', '#f1f8e9', '#ede7f6'],
        colorNames: ['Sunset Orange', 'Ocean Blue', 'Rose', 'Sage', 'Lilac'],
        style: 'Maxi',
        images: ['https://placehold.co/400x500/fff3e0/333?text=Boho+Orange', 'https://placehold.co/400x500/e0f7fa/333?text=Ocean+Blue', 'https://placehold.co/400x500/fce4ec/333?text=Rose+Boho'],
        description: 'Free-spirited bohemian beach dress with beautiful tassel details. Perfect for vacation and beach days.',
        features: ['Rayon breathable fabric', 'Tassel trim details', 'V-neckline', 'Loose relaxed fit', 'Side pockets']
    },
    {
        id: 'ld005',
        title: 'Party Sequin Mini Dress - Glitter Bodycon',
        price: 1200,
        originalPrice: 2200,
        discount: 45,
        rating: 4.9,
        sold: 800,
        category: 'ladies-dress',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ffd700', '#c0c0c0', '#000000', '#b71c1c', '#1a237e'],
        colorNames: ['Gold', 'Silver', 'Black', 'Red', 'Royal Blue'],
        style: 'Mini',
        images: ['https://placehold.co/400x500/ffd700/333?text=Gold+Sequin', 'https://placehold.co/400x500/c0c0c0/333?text=Silver+Sequin', 'https://placehold.co/400x500/000/ffd700?text=Black+Sequin'],
        description: 'Dazzling sequin bodycon dress for parties and special occasions. Turn heads with this stunning piece.',
        features: ['All-over sequin embellishment', 'Bodycon fit', 'Back zipper', 'Lined interior', 'Above knee length']
    },
    {
        id: 'ld006',
        title: 'Cotton Kurti Style Dress - Traditional Embroidery',
        price: 580,
        originalPrice: 950,
        discount: 39,
        rating: 4.6,
        sold: 3200,
        category: 'ladies-dress',
        sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
        colors: ['#ffffff', '#1a237e', '#c62828', '#2e7d32', '#ff6f00'],
        colorNames: ['White', 'Navy', 'Maroon', 'Green', 'Mustard'],
        style: 'Kurti',
        images: ['https://placehold.co/400x500/fff/333?text=White+Kurti', 'https://placehold.co/400x500/1a237e/fff?text=Navy+Kurti', 'https://placehold.co/400x500/c62828/fff?text=Maroon+Kurti'],
        description: 'Beautiful cotton kurti with traditional embroidery work. Comfortable for daily wear and festive occasions.',
        features: ['Pure cotton fabric', 'Hand embroidery work', 'Side slits', 'Comfortable loose fit', 'Available in plus sizes']
    },
    {
        id: 'ld007',
        title: 'Wrap Dress - Elegant V-Neck Midi Length',
        price: 890,
        originalPrice: 1600,
        discount: 44,
        rating: 4.7,
        sold: 1100,
        category: 'ladies-dress',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#d32f2f', '#1976d2', '#388e3c', '#000000', '#7b1fa2'],
        colorNames: ['Red', 'Blue', 'Green', 'Black', 'Purple'],
        style: 'Midi',
        images: ['https://placehold.co/400x500/d32f2f/fff?text=Red+Wrap', 'https://placehold.co/400x500/1976d2/fff?text=Blue+Wrap', 'https://placehold.co/400x500/388e3c/fff?text=Green+Wrap'],
        description: 'Classic wrap dress with elegant V-neckline. Universally flattering silhouette that suits all body types.',
        features: ['True wrap design', 'Self-tie waist belt', 'Midi length', 'Jersey stretch fabric', 'Flutter sleeves']
    },
    {
        id: 'ld008',
        title: 'Denim Shirt Dress - Casual Button-Down Style',
        price: 720,
        originalPrice: 1250,
        discount: 42,
        rating: 4.4,
        sold: 1900,
        category: 'ladies-dress',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['#1565c0', '#42a5f5', '#90caf9', '#000000'],
        colorNames: ['Dark Wash', 'Medium Wash', 'Light Wash', 'Black Denim'],
        style: 'Midi',
        images: ['https://placehold.co/400x500/1565c0/fff?text=Dark+Denim', 'https://placehold.co/400x500/42a5f5/fff?text=Medium+Wash', 'https://placehold.co/400x500/90caf9/333?text=Light+Wash'],
        description: 'Versatile denim shirt dress for casual everyday style. Can be worn as a dress or open as a jacket.',
        features: ['100% cotton denim', 'Button-down front', 'Roll-up sleeves', 'Belt loops with belt', 'Two chest pockets']
    }
];

// Get all products combined
function getAllProducts() {
    return [...phoneCovers, ...ladiesDresses];
}
